/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.fafic.sd;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.net.MalformedURLException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author luanl
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public String botão_atual = "";
    public int X_press = 0;
    public int O_press = 0;
    public String ultima_jogada = "";
    public static int jogadaCliente;
    public String id = "";

    boolean vencedor = false;

    public static String[][] tabuleiro = new String[3][3];

    public Principal() {
        Server s = new Server();
        s.iniciar();

        id = JOptionPane.showInputDialog("Digite o IP: ");
        initComponents();
        limparVetor();

        deletar();

        //deltetar
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            public void run() {
                ler_Arquivo();
                deletar();
            }

        }, 1000, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_X = new javax.swing.JButton();
        btn_O = new javax.swing.JButton();
        btnrecomecar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("        JOGO DA VELHA");

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });

        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });

        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });

        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });

        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });

        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-x-50.png")));
        btn_X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XMouseClicked(evt);
            }
        });
        btn_X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XActionPerformed(evt);
            }
        });

        btn_O.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-o-50.png")));
        btn_O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_X, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btn_O, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_X, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_O, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnrecomecar.setText("REINICIAR");
        btnrecomecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecomecarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnrecomecar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(138, 138, 138))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnrecomecar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn_XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XActionPerformed
        botão_atual = "x";
        X_press = 1;
        O_press = 0;

//        ler_Arquivo();

    }//GEN-LAST:event_btn_XActionPerformed

    private void btn_OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OActionPerformed
        botão_atual = "o";
        X_press = 0;
        O_press = 1;

//        ler_Arquivo();

    }//GEN-LAST:event_btn_OActionPerformed

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        colocarImagem(btn1, 0, 0, 1);
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        colocarImagem(btn2, 0, 1, 2);
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        colocarImagem(btn3, 0, 2, 3);       // TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        colocarImagem(btn4, 1, 0, 4);  // TODO add your handling code here:
    }//GEN-LAST:event_btn4MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        colocarImagem(btn5, 1, 1, 5);     // TODO add your handling code here:
    }//GEN-LAST:event_btn5MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        colocarImagem(btn6, 1, 2, 6);
    }//GEN-LAST:event_btn6MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        colocarImagem(btn7, 2, 0, 7);     // TODO add your handling code here:
    }//GEN-LAST:event_btn7MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        colocarImagem(btn8, 2, 1, 8);   // TODO add your handling code here:
    }//GEN-LAST:event_btn8MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        colocarImagem(btn9, 2, 2, 9);       // TODO add your handling code here:
    }//GEN-LAST:event_btn9MouseClicked

    private void btnrecomecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecomecarActionPerformed
        limparVetor();
        btn1.setIcon(null);
        btn2.setIcon(null);
        btn3.setIcon(null);
        btn4.setIcon(null);
        btn5.setIcon(null);
        btn6.setIcon(null);
        btn7.setIcon(null);
        btn8.setIcon(null);
        btn9.setIcon(null);
    }//GEN-LAST:event_btnrecomecarActionPerformed

    private void btn_XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XMouseClicked

// TODO add your handling code here:
    }//GEN-LAST:event_btn_XMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btn_O;
    private javax.swing.JButton btn_X;
    private javax.swing.JButton btnrecomecar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    public void colocarImagem(JButton nomeVariavel, int px, int py, int codigo) {

        if (nomeVariavel.getIcon() == null) {
            if (botão_atual.equals("x") && X_press == 1 && !ultima_jogada.equals("x")) {
                try {
                    nomeVariavel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-x-50.png")));
                    ultima_jogada = "x";

                    tabuleiro[px][py] = "X";

                    vencedor = verJogada("X", px, py);

                    if (vencedor) {
                        printVencedor("X");
                    }

                    IMultiplayer jogar = null;
                    try {

//                        Path caminho = Paths.get("C:/Users/natan/Documents/NetBeansProjects/JogoDaVelha-SD/host.txt");
//
//                        byte[] texto = Files.readAllBytes(caminho);
//                        String ip = new String(texto);
                        System.out.println(id);
                        jogar = (IMultiplayer) Naming.lookup("rmi://" + id + ":3000/jogar");
                    } catch (NotBoundException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (MalformedURLException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    jogar.verificaSimbolo(codigo, botão_atual);
                    btn_O.setEnabled(false);

                } catch (RemoteException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else if (botão_atual.equals("o") && O_press == 1 && !ultima_jogada.equals("o")) {
                try {
                    nomeVariavel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-o-50.png")));

                    ultima_jogada = "o";
                    tabuleiro[px][py] = "O";

                    vencedor = verJogada("O", px, py);

                    if (vencedor) {
                        printVencedor("O");
                    }

                    IMultiplayer jogar = null;
                    try {

//                        Path caminho = Paths.get("C:/Users/natan/Documents/NetBeansProjects/JogoDaVelha-SD/host.txt");
//
//                        byte[] texto = Files.readAllBytes(caminho);
//                        String ip = new String(texto);
                        jogar = (IMultiplayer) Naming.lookup("rmi://" + id + ":3000/jogar");

                    } catch (NotBoundException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (MalformedURLException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    jogar.verificaSimbolo(codigo, botão_atual);
                    btn_X.setEnabled(false);

                } catch (RemoteException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (X_press == 0 && O_press == 0) {
                JOptionPane.showMessageDialog(null, "Por favor escolha 'X' ou 'O' antes!");
            } else {
                JOptionPane.showMessageDialog(null, "Vez do outro jogador!");

            }
        } else {
            JOptionPane.showMessageDialog(null, "AQUI JA FOI!!");

        }

    }

    public void ReceberValor(int codigoLa, String escolha) {
        System.out.println("codigo la  " + codigoLa);
        JButton botao = null;
        switch (codigoLa) {
            case 1:
                botao = btn1;
                colocarImagemCliente(botao, 0, 0, escolha);
                break;
            case 2:
                botao = btn2;
                colocarImagemCliente(botao, 0, 1, escolha);
                break;
            case 3:
                botao = btn3;
                colocarImagemCliente(botao, 0, 2, escolha);
                break;
            case 4:
                botao = btn4;
                colocarImagemCliente(botao, 1, 0, escolha);
                break;
            case 5:
                botao = btn5;
                colocarImagemCliente(botao, 1, 1, escolha);
                break;
            case 6:
                botao = btn6;
                colocarImagemCliente(botao, 1, 2, escolha);
                break;
            case 7:
                botao = btn7;
                colocarImagemCliente(botao, 2, 0, escolha);
                break;
            case 8:
                botao = btn8;
                colocarImagemCliente(botao, 2, 1, escolha);
                break;
            case 9:
                botao = btn9;
                colocarImagemCliente(botao, 2, 2, escolha);
                break;
        }
    }

    public void colocarImagemCliente(JButton nomeVariavel, int px, int py, String bt_atual) {

        if (nomeVariavel.getIcon() == null) {
            if (bt_atual.equals("x") && !ultima_jogada.equals("x")) {
                nomeVariavel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-x-50.png")));

                ultima_jogada = "o";
                tabuleiro[px][py] = "X";

                vencedor = verJogada("X", px, py);
                ultima_jogada = "x";

                if (vencedor) {
                    printVencedor("X");
                }

            } else if (bt_atual.equals("o") && !ultima_jogada.equals("o")) {
                nomeVariavel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-o-50.png")));

                ultima_jogada = "o";
                tabuleiro[px][py] = "O";

                vencedor = verJogada("O", px, py);

                if (vencedor) {
                    printVencedor("O");
                }

            } else if (X_press == 0 && O_press == 0) {
                JOptionPane.showMessageDialog(null, "Por favor escolha 'X' ou 'O' antes!");
            } else {
                JOptionPane.showMessageDialog(null, "Vez do outro jogador!");

            }
        }

    }

    public void printVencedor(String v) {
        JOptionPane.showMessageDialog(null, "O JOGADOR " + v + " VENCEU!!");
    }

    public static boolean verJogada(String simbolo, int x, int y) {
        boolean vencedor = false;
        if (x == 0 && y == 0) {
            if ((tabuleiro[0][1].equals(simbolo) && tabuleiro[0][2].equals(simbolo))
                    || (tabuleiro[1][0].equals(simbolo) && tabuleiro[2][0].equals(simbolo))
                    || (tabuleiro[1][1].equals(simbolo) && tabuleiro[2][2].equals(simbolo))) {
                vencedor = true;
            }
        }
        if (x == 0 && y == 1) {
            if ((tabuleiro[0][0].equals(simbolo) && tabuleiro[0][2].equals(simbolo))
                    || (tabuleiro[1][1].equals(simbolo) && tabuleiro[2][1].equals(simbolo))) {
                vencedor = true;
            }

        }
        if (x == 0 && y == 2) {
            if ((tabuleiro[0][1].equals(simbolo) && tabuleiro[0][0].equals(simbolo))
                    || (tabuleiro[1][2].equals(simbolo) && tabuleiro[2][2].equals(simbolo))
                    || (tabuleiro[1][1].equals(simbolo) && tabuleiro[2][0].equals(simbolo))) {
                vencedor = true;
            }
        }

        if (x == 1 && y == 0) {
            if ((tabuleiro[0][0].equals(simbolo) && tabuleiro[2][0].equals(simbolo))
                    || (tabuleiro[1][1].equals(simbolo) && tabuleiro[1][2].equals(simbolo))) {
                vencedor = true;
            }
        }
        if (x == 1 && y == 1) {
            if ((tabuleiro[0][1].equals(simbolo) && tabuleiro[2][1].equals(simbolo))
                    || (tabuleiro[1][0].equals(simbolo) && tabuleiro[1][2].equals(simbolo))
                    || (tabuleiro[0][0].equals(simbolo) && tabuleiro[2][2].equals(simbolo))
                    || (tabuleiro[0][2].equals(simbolo) && tabuleiro[2][0].equals(simbolo))) {
                vencedor = true;
            }
        }
        if (x == 1 && y == 2) {
            if ((tabuleiro[0][2].equals(simbolo) && tabuleiro[2][2].equals(simbolo))
                    || (tabuleiro[1][1].equals(simbolo) && tabuleiro[1][0].equals(simbolo))) {
                vencedor = true;
            }
        }

        if (x == 2 && y == 0) {
            if ((tabuleiro[0][0].equals(simbolo) && tabuleiro[1][0].equals(simbolo))
                    || (tabuleiro[2][1].equals(simbolo) && tabuleiro[2][2].equals(simbolo))
                    || (tabuleiro[1][1].equals(simbolo) && tabuleiro[0][2].equals(simbolo))) {
                vencedor = true;
            }
        }
        if (x == 2 && y == 1) {
            if ((tabuleiro[2][0].equals(simbolo) && tabuleiro[2][2].equals(simbolo))
                    || (tabuleiro[1][1].equals(simbolo) && tabuleiro[0][1].equals(simbolo))) {
                vencedor = true;
            }
        }
        if (x == 2 && y == 2) {
            if ((tabuleiro[2][1].equals(simbolo) && tabuleiro[2][0].equals(simbolo))
                    || (tabuleiro[1][2].equals(simbolo) && tabuleiro[0][2].equals(simbolo))
                    || (tabuleiro[1][1].equals(simbolo) && tabuleiro[0][0].equals(simbolo))) {
                vencedor = true;
            }
        }
        return vencedor;
    }

    public void limparVetor() {
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                tabuleiro[i][j] = "-";
            }
        }
    }

    public static int valor(int velor) {
        jogadaCliente = velor;

        System.out.println(velor + " Principal");
        System.out.println(jogadaCliente + " Principal222");
        return velor;
    }

    public void ler_Arquivo() {
        boolean liberar_ler_arquivo = false;
        try {
            File file = new File("codigoCliente.txt");

            if (file.exists()) {

                FileReader leitura = new FileReader("codigoCliente.txt");

                BufferedReader br = new BufferedReader(leitura);

                int enviar_Codigo = Integer.parseInt(br.readLine());
                String enviar_Simbolo = br.readLine();
                ReceberValor(enviar_Codigo, enviar_Simbolo);
            }

        } catch (IOException ex) {
            Logger.getLogger(Multiplayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void deletar() {

        //deletar
        File file = new File("codigoCliente.txt");

        if (file.exists()) {
            file.delete();

        }
    }

}
